// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	aboutpage: NamespaceAboutpageTranslation
}

type RootTranslation = {
	/**
	 * Hi {name}!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
}

export type NamespaceAboutpageTranslation = {
	/**
	 * This page is about stuff!
	 */
	DESCRIPTION: string
}

export type Namespaces =
	| 'aboutpage'

type DisallowNamespaces = {
	/**
	 * reserved for 'aboutpage'-namespace\
	 * you need to use the `./aboutpage/index.ts` file instead
	 */
	aboutpage?: "[typesafe-i18n] reserved for 'aboutpage'-namespace. You need to use the `./aboutpage/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Hi {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	aboutpage: {
		/**
		 * This page is about stuff!
		 */
		DESCRIPTION: () => LocalizedString
	}
}

export type Formatters = {}
